label: Documentation from Git
versions:
  latest:
    label: Latest
    sources:
      src1:
        type: git
        options:
          url: https://github.com/vtabary/docile.git
          branch: master
